Stask 3
JugglypuffM/Robots pull request #3
Opened 2024-04-09 10:28 UTC by JugglypuffM

2024-04-09 14:55 UTC, JugglypuffM commented on src/main/java/gui/game/GameVisualizer.java
> +    private int targetY = 100;
Это как будто не очень грамотное решение, но вызвать репейнт с аргументами низя, а самому рисовать не получается - он ломается с ошибкой изза того что графика оказывается null, и в общем не уверен можно ли сделать иначе

2024-04-16 18:10 UTC, vpyzhyanov commented on src/main/java/gui/game/GameVisualizer.java
> +    private int targetY = 100;
Почему одни и те же данные и там и тут?! А чем собственно занимается у вас модель? Бездельничает?

Рисовать вручную ничего не надо. Представление должно рисовать **модель**, притом самостоятельно.

2024-04-16 18:22 UTC, vpyzhyanov requested changes
есть замечания

2024-04-16 18:22 UTC, vpyzhyanov commented on src/main/java/gui/GameVisualizer.java
вот это поворот! Удалена модель. А может пожалеете её?

Если пользоваться перемещением файла, то git не будет отображать это как удаление

2024-04-16 18:22 UTC, vpyzhyanov commented on src/main/java/gui/game/GameController.java
> +    protected void onModelUpdateEvent()
1. Опять с инкапсуляцией проблемы
2. Однострочный метод состоящий из одной команды смысла иметь не может. Удалите его

2024-04-16 18:22 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +        model.addNewListener(visualizer);
окна должны сами уметь подписываться на нужные им события. Это не должно происходить извне. Тем более они все работают с одной моделью и подписаться на её изменение им ничего не стоит.

2024-04-16 18:22 UTC, vpyzhyanov commented on src/main/java/gui/game/GameModel.java
> +    public void addNewListener(PropertyChangeListener listener){
не хватает отступа между методами и полями

2024-04-16 18:22 UTC, vpyzhyanov commented on src/main/java/gui/game/GameModel.java
> +        support.firePropertyChange("targetPositionY", m_targetPositionY, p.y);
не самая лучшая идея разделять одну точку на 2 события. Они могут прийти не одновременно.

Зачем вообще разделять события? Достаточно одного события - изменения модели.

2024-04-16 18:22 UTC, vpyzhyanov commented on src/main/java/gui/game/GameVisualizer.java
> +                repaint();
лишняя операция. Изменение модели порождает событие, обработка которого вызывает перерисовку

2024-04-16 18:22 UTC, vpyzhyanov commented on src/main/java/gui/game/GameVisualizer.java
> +        targetY = model.getTargetPositionY();
не нужно ничего копировать

2024-04-16 18:23 UTC, vpyzhyanov commented
3 задача по прежнему не поддерживает функционал предыдущей задачи и вообще не сохраняет никакие состояния. Новое окно - не исключение

2024-04-22 06:53 UTC, JugglypuffM commented on src/main/java/gui/game/GameVisualizer.java
> +    private int targetY = 100;
И каким образом это можно сделать?
Метод paint, который должен быть переопределен для того чтобы отрисовка работала не может принимать аргукменты, т.к. в этом случае его сигнатура поменяется и он будет не переопределен, а перегружен, и в этом случае ничего работать не будет
И в следствии этого возникает вопрос - как из метода, который вызывается при получении обновлений, вызвать отрисовку, да еще и передать ей нужные аргументы при том что аргументы она принимать не может?

2024-04-22 19:22 UTC, vpyzhyanov commented on src/main/java/gui/game/GameVisualizer.java
> +    private int targetY = 100;
Всё очень просто, у класса есть поля, в которые можно сохранить какие-то важные данные. Например модель.
Метод paint при рисовании использует эту модель (точнее данные из неё).

А когда приходит событие изменения модели, мы просто вызываем `repaint()` и получаем новую картинку.

2024-04-22 19:32 UTC, vpyzhyanov requested changes
Как исправите небольшие замечания, можете мёрджить

2024-04-22 19:32 UTC, vpyzhyanov commented on src/main/java/gui/CoordinateWindow.java
> +            Logger.debug(e.getMessage());
прошу всегда писать человекочитаемые сообщения об ошибках

2024-04-22 19:32 UTC, vpyzhyanov commented on src/main/java/gui/game/GameModel.java
> +    public void addNewListener(PropertyChangeListener listener){
немного перестарались) Отступ между полями можно не делать. Иногда таким отступом можно группировать поля.

2024-04-22 19:32 UTC, vpyzhyanov commented on src/main/java/gui/game/GameModel.java
> +        support.firePropertyChange("targetPositionX", new Point(m_targetPositionX, m_targetPositionY), p);
имя события забыли актуализировать

2024-04-22 19:32 UTC, vpyzhyanov commented on src/main/java/save/Memorizable.java
> +public interface Memorizable {
А разве 2 задача у вас не смёрджена в main?... хотя нет смёрджена... в этом случае эти изменения не должны тут отображаться.... странно. Ну либо это GitHub так делает, в GitLab всё нормально.

2024-04-23 06:07 UTC, merged