Stask 4
JugglypuffM/Robots pull request #4
Opened 2024-04-23 06:55 UTC by JugglypuffM

2024-04-29 11:04 UTC, vpyzhyanov requested changes
В остальном всё хорошо.

2024-04-29 11:04 UTC, vpyzhyanov commented on src/main/java/log/LogWindowSource.java
>  public class LogWindowSource {
обратите внимание на JavaDoc (не надо делать вид, что вы его не заметили😉)

2024-05-06 17:37 UTC, JugglypuffM commented on src/main/java/log/LogWindowSource.java
>  public class LogWindowSource {
я честно его не заметил!

2024-05-14 20:26 UTC, vpyzhyanov requested changes
Исправлено неправильно(

Вы же были на паре. Я же рассказывал как это надо было делать, что пошло не так?

2024-05-14 20:26 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +            Logger.getDefaultLogSource().unregisterAllListeners();
это никак не решает проблему. При завершении работы приложения все ресурсы освобождаются

2024-05-20 09:32 UTC, JugglypuffM commented
Я поправил до пары, а потом как то не подумал)

2024-05-20 19:12 UTC, vpyzhyanov requested changes
почти получилось

2024-05-20 19:12 UTC, vpyzhyanov commented on src/main/java/log/LogWindowSource.java
> +            Objects.requireNonNull(reference.get()).onLogChanged();
Интересный ход, добавлять **гарантированный** NullPointerException в код, чтобы он возник в неожиданный момент времени и уронил всё приложение целиком))). А теперь объясните мне почему он **гарантированно** возникнет?

2024-05-22 14:13 UTC, JugglypuffM commented on src/main/java/log/LogWindowSource.java
> +            Objects.requireNonNull(reference.get()).onLogChanged();
Боже, как стыдно - я забыл проверить, что делает requireNonNull(его идея туда поставила, и я подумал, что "раз не подсвечивает, значит норм"). Исключение выбросится как раз этим методом, когда ссылаемый объект будет собран сборщиком и .get() вернет null

2024-05-22 18:35 UTC, vpyzhyanov commented on src/main/java/log/LogWindowSource.java
> +            Objects.requireNonNull(reference.get()).onLogChanged();
Правильно)

2024-05-22 18:36 UTC, vpyzhyanov commented
Задача принята

2024-05-23 10:22 UTC, merged