Stask 5
JugglypuffM/Robots pull request #5
Opened 2024-05-07 10:50 UTC by JugglypuffM

2024-05-14 20:33 UTC, vpyzhyanov requested changes
есть замечания

2024-05-14 20:33 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    public ResourceBundle bundle = ResourceBundle.getBundle("localization", new Locale("ru"));
то делает это поле в классе MainApplicationFrame? Ему тут явно не место. Это тёмная сторона ООП так-то, основной класс теперь ещё и за локализацию отвечает. Это должен делать отдельный класс

2024-05-14 20:33 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    public void changeLocale(Locale locale) {
где JavaDoc?

2024-05-14 20:33 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +            Logger.error("Locale change failed due to missing resources with message:\n" + e.getMessage());
лучше стек тоже выводить, он будет очень полезен при разборе ошибок

2024-05-14 20:33 UTC, vpyzhyanov commented on src/main/java/gui/menu/AppMenu.java
> +        super("Приложение");
А где локализация?

2024-05-14 20:33 UTC, vpyzhyanov commented on src/main/java/gui/menu/AppMenu.java
> +        getAccessibleContext().setAccessibleDescription("Команды приложению");
И тут нет

2024-05-14 20:33 UTC, vpyzhyanov commented on src/main/java/gui/menu/LocaleMenu.java
> +        super("Язык");
Это же новый класс, почему нет локализации?!

2024-05-14 20:33 UTC, vpyzhyanov commented on src/main/java/gui/menu/TestMenu.java
> +        addLogMessageItem.addActionListener((event) -> Logger.debug("Новая строка"));
нигде нет локализации, печаль( Это точно задача на локализацию?

2024-05-20 10:35 UTC, JugglypuffM commented on src/main/java/gui/menu/TestMenu.java
> +        addLogMessageItem.addActionListener((event) -> Logger.debug("Новая строка"));
да я както не подумал, что значения по умолчания надо менять)

2024-05-20 19:29 UTC, vpyzhyanov requested changes
не исправлено(

2024-05-20 19:29 UTC, vpyzhyanov commented on src/main/java/gui/menu/LocaleMenu.java
> +        super("");
Так себе исправление. Если вдруг метод по смене локали не сработает то класс вообще останется без названия. Во всех остальных местах тоже.

Правильно будет использовать ResourceBundle **везде**, а метод localeChange вызывать только при смене локали (у него даже название говорит о том, что он вызывается при смене локали)

2024-05-20 19:29 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +        return localeManager;
нарушение инкапсуляции. Лучше бы `LocaleManager` сделали сиглтоном

2024-05-20 19:29 UTC, vpyzhyanov commented on src/main/java/gui/menu/LocaleMenu.java
> +        localeChange(LocaleManager.getBundle());
метод не должен вызываться в конструторе

2024-05-20 19:29 UTC, vpyzhyanov commented on src/main/java/gui/menu/TestMenu.java
> +        addLogMessageItem.addActionListener((event) -> Logger.debug("Новая строка"));
не исправлено!

2024-05-20 19:29 UTC, vpyzhyanov commented on src/main/java/gui/menu/TestMenu.java
> +        localeChange(LocaleManager.getBundle());
разве вы не чувствуете потерю ООП, когда пишете в куче мест абсолютно одинаковый код?! А надо бы уже чувствовать

2024-05-20 19:29 UTC, vpyzhyanov commented on src/main/java/localization/LocaleManager.java
> + * Has static method to get access to resource bundle
Какой кошмар. Помянем ООП(((

2024-05-20 19:29 UTC, vpyzhyanov commented on src/main/java/localization/LocaleManager.java
> +    private static ResourceBundle bundle = ResourceBundle.getBundle("localization", Locale.getDefault());
фу, какая гадость это ваш `static`. Применён совершенно неуместно. Бедное ООП и принципы SOLID, нам будет вас не хватать(((

2024-05-20 19:29 UTC, vpyzhyanov commented on src/main/java/localization/LocaleManager.java
> +        return bundle;
лучше бы тут был 
```java
public static String getString(String messageCode) {
        return getInstance().getBundle().getString(messageCode);
}
```

2024-05-22 16:19 UTC, JugglypuffM commented on src/main/java/localization/LocaleManager.java
> +    private static ResourceBundle bundle = ResourceBundle.getBundle("localization", Locale.getDefault());
Не очень понимаю какой именно принцип я нарушил, объясните пожалуйста

2024-05-22 16:20 UTC, JugglypuffM commented on src/main/java/localization/LocaleManager.java
> +    private static ResourceBundle bundle = ResourceBundle.getBundle("localization", Locale.getDefault());
static я сделал чтобы не прокидывать во все локализуемые классы ссылку на него - и это действительно не по ооп, но вы сами говорили, что оно может быть неудобным, и сняли запрет со статиков.

Вообще не отрицаю, что мог применить его неуместно, но не знаю как тут можно сделать лучше)

2024-05-22 18:40 UTC, vpyzhyanov commented on src/main/java/localization/LocaleManager.java
> +    private static ResourceBundle bundle = ResourceBundle.getBundle("localization", Locale.getDefault());
> Не очень понимаю какой именно принцип я нарушил, объясните пожалуйста

Это принцип открытой закрытости. Кстати про это было в лекциях у Александра Владимировича.

> static я сделал чтобы не прокидывать во все локализуемые классы ссылку на него - и это действительно не по ооп, но вы сами говорили, что оно может быть неудобным, и сняли запрет со статиков.

Я уже предложил удобный вариант - сделать синглтон) Вариант очень удобный, и в этом случае очень уместный

2024-05-22 18:51 UTC, vpyzhyanov requested changes
Старания почему-то не ко всем замечаниям применены(

2024-05-22 18:51 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +        String[] options = {ResourceBundle.getBundle("localization", localeManager.getCurrentLocale()).getString("exitDialog.yes"), ResourceBundle.getBundle("localization", localeManager.getCurrentLo
кучу раз дублируется один и тот же вызов `ResourceBundle.getBundle("localization", localeManager.getCurrentLocale()).getString(...)`. В одном из ранее сделанных замечаний я предлагал как это сделать лучше.

2024-05-22 18:51 UTC, vpyzhyanov commented on src/main/java/gui/menu/AppMenu.java
> +        setText(ResourceBundle.getBundle("localization", Locale.getDefault()).getString(String.format("%s.label", CLASSNAME)));
В этом случае лучше использовать конкатенацию, а не `String.format`, т.к. конкатенация работает гораздо быстрее, чем парсинг шаблона. А ещё она кешируется, а значение сформированное по шаблону - нет.

2024-05-22 18:51 UTC, vpyzhyanov commented on src/main/java/gui/menu/LocaleMenu.java
> +        super("");
Не исправлено!!! =(((((

2024-05-22 18:51 UTC, vpyzhyanov commented on src/main/java/gui/menu/TestMenu.java
>          super("");
не исправлено(

2024-05-22 18:51 UTC, vpyzhyanov commented on src/main/java/gui/menu/TestMenu.java
> +        addLogMessageItem.addActionListener((event) -> Logger.debug("Новая строка"));
опять не исправлено! Второй раз не исправляется замечание, притом без какого либо обоснования. За такие вещи вам полагается предупреждение! С последующим ущербом для репутации.

2024-05-22 18:51 UTC, vpyzhyanov commented on src/main/java/gui/windows/CoordinateWindow.java
>          super("", true, true, true, true);
не исправлено(

2024-05-22 18:51 UTC, vpyzhyanov commented on src/main/java/gui/windows/GameWindow.java
>          super("", true, true, true, true);
тоже

2024-05-22 18:51 UTC, vpyzhyanov commented on src/main/java/localization/LocaleManager.java
> +        return currentLocale;
лучше бы менеджер локалей локализованные сообщения отдавал, а не текущую локаль. А то получается класс для управления локалью есть, но ей управляют все, но только не он(

2024-05-22 18:58 UTC, JugglypuffM commented on src/main/java/gui/menu/TestMenu.java
> +        addLogMessageItem.addActionListener((event) -> Logger.debug("Новая строка"));
Я не понимаю, что происходит, но это кажется какой-то баг - я не могу найти эти строки ни в коде локально ни в гитхабе.
Даже если во вкладке "изменённые файлы" если посмотреть на этот комментарий - он отображается рядом с другим кодом, не тем что выделен в комментарии

2024-05-23 07:17 UTC, JugglypuffM commented on src/main/java/localization/LocaleManager.java
> +    private static ResourceBundle bundle = ResourceBundle.getBundle("localization", Locale.getDefault());
я просто вообще не сразу(если честно только сейчас) понял, что именно вы предлагали)

2024-05-23 11:39 UTC, vpyzhyanov requested changes

2024-05-23 11:39 UTC, vpyzhyanov commented on src/main/java/gui/menu/MenuBar.java
> +        add(new LocaleMenu((JDesktopPane) mainframe.getContentPane(), this));
любой cast делать опасно, ведь это потенциальный ClassCastException. Лучше просто mainframe передать, и дальше уже разбираться с тем что вам от него нужно.

2024-05-23 11:39 UTC, vpyzhyanov commented on src/main/java/gui/menu/TestMenu.java
> +        addLogMessageItem.addActionListener((event) -> Logger.debug("Новая строка"));
О_о почему снова не исправлено? В чём проблема?

2024-05-24 07:32 UTC, JugglypuffM commented on src/main/java/gui/menu/MenuBar.java
> +        add(new LocaleMenu((JDesktopPane) mainframe.getContentPane(), this));
Каст перенес в LocaleMenu, но просто mainframe передавать не вижу смысла - menuBar в любом случае нужно передавть через this, тк как в mainframe он еще не инициализирован, а кроме него нужен только contentPane и как бы зачен нам целый mainframe

2024-05-24 07:32 UTC, JugglypuffM commented on src/main/java/gui/menu/TestMenu.java
> +        addLogMessageItem.addActionListener((event) -> Logger.debug("Новая строка"));
вроде наконец исправил)

2024-06-01 20:01 UTC, vpyzhyanov commented
Задача принята

2024-06-04 21:54 UTC, merged