Stask 6
JugglypuffM/Robots pull request #6
Opened 2024-05-22 13:46 UTC by JugglypuffM

2024-05-22 19:08 UTC, vpyzhyanov requested changes
есть небольшие замечания

2024-05-22 19:08 UTC, vpyzhyanov commented on src/main/java/gui/JarClassLoader.java
> +        byte[] buffer = new byte[1000000];
не многоват ли буфер? Обычно буфер делают размера одной из степеней двойки, например 2048, так эффективнее

2024-05-22 19:08 UTC, vpyzhyanov commented on src/main/java/gui/JarClassLoader.java
> +        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
некорректная работа с потоками ввода-вывода. Исключений быть не может даже для такого простого класса.

2024-05-22 19:08 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    GameVisualizer gameVisualizer;
зачем нарушили инкапсуляцию?

2024-05-22 19:08 UTC, vpyzhyanov commented on src/main/java/gui/menu/RobotLoadMenu.java
> +        super("");
нет названия

2024-05-22 19:08 UTC, vpyzhyanov commented on src/main/java/gui/menu/RobotLoadMenu.java
> +                    + Arrays.toString(e.getStackTrace()));
в таком виде в логе стектрейс бесполезен. Лучше его выводить отдельно с форматированием.

2024-05-23 10:44 UTC, JugglypuffM commented on src/main/java/gui/menu/RobotLoadMenu.java
> +        super("");
оно как бы есть, просто устанавливается неправильным образом т.к. я эту ветку отделил от прошлой, которая не доделана
вот такую ситуацию я имел ввиду, когда мы говорили про необходимость начинать новую задачу от последней(возможно не законченной), а не от мейна - я не могу сделать правильно, потому что еще не знаю как)

2024-05-23 11:45 UTC, vpyzhyanov requested changes

2024-05-23 11:45 UTC, vpyzhyanov commented on src/main/java/log/Logger.java
> +                    + Arrays.toString(stackTrace).replace(",", ",\n")
А могли не изобретать велосипеды, а использовать `java.lang.Throwable#printStackTrace(java.io.PrintStream)`

2024-05-23 11:45 UTC, vpyzhyanov commented on src/main/java/log/Logger.java
> +                + Arrays.toString(stackTrace).replace(",", ",\n")
дублировать код тоже не обязательно

2024-05-24 07:49 UTC, JugglypuffM commented on src/main/java/log/Logger.java
> +                    + Arrays.toString(stackTrace).replace(",", ",\n")
я хотел этим воспользоваться, но он принимает PrintStream, а Logger таковым не является и что с этим делать я не придумал

2024-06-01 20:03 UTC, vpyzhyanov commented on src/main/java/log/Logger.java
> +                    + Arrays.toString(stackTrace).replace(",", ",\n")
Ну ничего, когда-нибудь вы прочитаете JavaDoc и поймёте как сделать строку, с помощью PrintStream)

2024-06-01 20:06 UTC, vpyzhyanov commented
По замечаниям ок. А загрузку классов решили не исправлять?

2024-06-04 21:59 UTC, merged